name: saravanaram
description: ""
url: http://saravanaram.net
download: ""
social:
  github: saravanaram
  email: saravanan.r@outlook.com
  facebook:
  twitter: saravanaram
  instagram:
  tumblr:
author:
  name: saravanan
  bio: ""
  email: saravanan.r@outlook.com
  image: /assets/images/author.jpg
  github: saravanaram
  facebook: 
  twitter: saravanaram
  instagram:
  tumblr:
  show_on_post: true

system:
  fb_app: ""
permalink: /:title/

sass:
  style: compressed
paginate: 6
paginate_path: "/:num/"
markdown: kramdown
syntax_highlighter: rouge
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
